In [2]:
from bs4 import BeautifulSoup
import requests

In [3]:
url = "https://grokipedia.com/page/List_of_largest_companies_in_the_United_States_by_revenue"

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [4]:
print(soup.prettify())

<!DOCTYPE html>
<html class="dark" lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1, interactive-widget=resizes-content" name="viewport"/>
  <title>
   List of largest companies in the United States by revenue â Grokipedia
  </title>
  <meta content="The list of largest companies in the United States by revenue is an annual ranking published by Fortune magazine, featuring the top 500 U.S.-headquartered corporations ordered by total revenue generat" name="description"/>
  <link href="https://grokipedia.com/page/List_of_largest_companies_in_the_United_States_by_revenue" rel="canonical"/>
  <link href="/favicon.ico" rel="icon" sizes="48x48"/>
  <link href="/icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
  <link href="/icon-512x512.png" rel="icon" sizes="512x512" type="image/png"/>
  <link href="/icon-192x192.png" rel="apple-touch-icon"/>
  <link href="/manifest.json" rel="manifest"/>
  <!-- OG -->
  <meta content="List of largest companies in the United States by revenue â Grokipedia" property="og:title"/>
  <meta content="The list of largest companies in the United States by revenue is an annual ranking published by Fortune magazine, featuring the top 500 U.S.-headquartered corporations ordered by total revenue generat" property="og:description"/>
  <meta content="https://grokipedia.com/page/List_of_largest_companies_in_the_United_States_by_revenue" property="og:url"/>
  <meta content="Grokipedia" property="og:site_name"/>
  <meta content="en_US" property="og:locale"/>
  <meta content="article" property="og:type"/>
  <meta content="https://grokipedia.com/icon-512x512.png" property="og:image"/>
  <meta content="512" property="og:image:width"/>
  <meta content="512" property="og:image:height"/>
  <meta content="Grokipedia" property="og:image:alt"/>
  <!-- Twitter -->
  <meta content="summary" name="twitter:card"/>
  <meta content="@Grokipedia" name="twitter:creator"/>
  <meta content="List of largest companies in the United States by revenue â Grokipedia" name="twitter:title"/>
  <meta content="The list of largest companies in the United States by revenue is an annual ranking published by Fortune magazine, featuring the top 500 U.S.-headquartered corporations ordered by total revenue generat" name="twitter:description"/>
  <meta content="https://grokipedia.com/icon-512x512.png" name="twitter:image"/>
  <!-- Robots -->
  <meta content="index, follow" name="robots"/>
  <meta content="index, follow, max-snippet:-1" name="googlebot"/>
  <!-- Schema.org WebSite structured data (for sitelinks search box) -->
  <!-- Theme: apply synchronously before first paint to prevent flash -->
  <script nonce="9Y/jJR93aRXgpMCoBIpWeg==">
   (function(){
        var t = localStorage.getItem('theme');
        if (t === 'light') document.documentElement.classList.remove('dark');
        else if (t === 'dark') document.documentElement.classList.add('dark');
        else {
          // system preference
          if (window.matchMedia('(prefers-color-scheme: light)').matches) {
            document.documentElement.classList.remove('dark');
          } else {
            document.documentElement.classList.add('dark');
          }
        }
      })();
  </script>
  <!-- KaTeX CSS for server-rendered math (loaded from CDN, fonts only) -->
  <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.css" rel="stylesheet"/>
  <link href="/_astro/activity.Clg-wNwt.css" rel="stylesheet"/>
  <link href="/_astro/activity.B8hnKYSI.css" rel="stylesheet"/>
 </head>
 <body class="flex h-[100svh] w-full flex-col bg-surface-base text-fg-primary antialiased" data-auth="0">
  <!-- Analytics: UAS + page views + action events (~400 bytes gzipped) -->
  <script nonce="9Y/jJR93aRXgpMCoBIpWeg==">
   (function(){
      var t0=Date.now(),active=0,idle=false,last=t0,thr=0;
      var mob=window.innerWidth<768?1:0;
      var auth=document.body.getAttribute('data-auth')==='1'?1:0;

      // Referrer classification (bucketed to avoid cardinality explosion)
      var ref=document.referrer,r='direct';
      if(ref){try{var h=new URL(ref).hostname;
        if(/google\./i.test(h))r='google';
        else if(/bing\./i.test(h))r='bing';
        else if(/duckduckgo\./i.test(h))r='duckduckgo';
        else if(/x\.com|twitter\.com/i.test(h))r='x';
        else if(/reddit\.com/i.test(h))r='reddit';
        else if(/claude\.ai|anthropic/i.test(h))r='claude';
        else if(/chatgpt\.com|openai/i.test(h))r='chatgpt';
        else if(/grokipedia\.com/i.test(h))r='internal';
        else r='other';
      }catch(e){r='other';}}

      // Browser language (primary, 2-letter code)
      var lang=(navigator.language||'').slice(0,2).toLowerCase()||'unknown';

      function tick(){
        var n=Date.now();
        if(n-thr<200)return;thr=n;
        if(!idle)active+=n-last;
        last=n;idle=false;
      }
      document.addEventListener('visibilitychange',function(){
        if(document.hidden){tick();idle=true;}else{last=Date.now();idle=false;}
      });
      ['click','scroll','keydown','touchstart'].forEach(function(e){
        document.addEventListener(e,tick,{passive:true,capture:true});
      });
      addEventListener('pagehide',function(){
        tick();
        var p=location.pathname,s=p.indexOf('/page/')===0?p.slice(6):p;
        var perf=performance.getEntriesByType&&performance.getEntriesByType('navigation');
        var lt=perf&&perf[0]?perf[0].loadEventEnd/1000:0;
        // Auto-translate detection: Chrome/Edge add class "translated-*" and change html lang
        var docLang=document.documentElement.lang||'';
        var translated=(docLang&&docLang!=='en'&&
          document.documentElement.className.indexOf('translated')!==-1)?docLang:'';
        navigator.sendBeacon('/api/analytics',new Blob([JSON.stringify({
          s:s,p:p,a:Math.round(active/1000),d:Math.round((Date.now()-t0)/1000),
          l:Math.round(lt*100)/100,u:auth,m:mob,
          r:r,lang:lang,translated:translated
        })],{type:'application/json'}));
      });
      // Global event tracker for discrete actions
      window.__ev=function(e,q){
        navigator.sendBeacon('/api/ev',new Blob([JSON.stringify({e:e,q:q||'',m:mob})],{type:'application/json'}));
      };
    })();
  </script>
  <script nonce="9Y/jJR93aRXgpMCoBIpWeg==" type="application/ld+json">
   {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Grokipedia","item":"https://grokipedia.com"},{"@type":"ListItem","position":2,"name":"List of largest companies in the United States by revenue","item":"https://grokipedia.com/page/List_of_largest_companies_in_the_United_States_by_revenue"}]}
  </script>
  <script nonce="9Y/jJR93aRXgpMCoBIpWeg==" type="application/ld+json">
   {"@context":"https://schema.org","@type":"Article","headline":"List of largest companies in the United States by revenue","url":"https://grokipedia.com/page/List_of_largest_companies_in_the_United_States_by_revenue","publisher":{"@type":"Organization","name":"Grokipedia","url":"https://grokipedia.com"},"dateModified":"2026-01-14T01:23:59.000Z"}
  </script>
  <header class="bg-surface-base fixed top-0 z-50 h-16 w-full">
   <!-- Desktop Header (md+) â matches Next.js grid-cols-[1fr_3fr_1fr] -->
   <div class="hidden h-full w-full grid-cols-[1fr_3fr_1fr] items-center gap-4 !py-0 md:grid max-w-screen-3xl mx-auto px-4 py-6 sm:px-6">
    <!-- Logo -->
    <div class="justify-self-start">
     <a class="cursor-pointer" href="/">
      <svg aria-label="Grokipedia" class="" fill="none" viewbox="0 0 786 179" width="180" xmlns="http://www.w3.org/2000/svg">

In [5]:
soup.find_all('table')[1]

<table class="w-full border-collapse text-sm"><thead class="border-border-l1 border-b bg-surface-l1"><tr class="divide-border-l1 divide-x bg-surface-l1"><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Rank</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Company Name</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Net Profit ($B)</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Revenue ($B)</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Industry</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Headquarters</span></th></tr>
</thead><tbody class="divide-border-l1 divide-y"><tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">1</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Alphabet Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">124.3</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">385.5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Communication Services</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Mountain View, CA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">2</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Apple Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">112.0</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">416.2</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Information Technology</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Cupertino, CA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">3</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Microsoft Corporation</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">104.9</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">293.8</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Information Technology</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Redmond, WA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">4</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">NVIDIA Corporation</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">86.6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">165.2</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Information Technology</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Santa Clara, CA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Amazon.com Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">76.5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">691.3</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Consumer Discretionary</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Seattle, WA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Berkshire Hathaway Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">67.5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">372.1</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Financials</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Omaha, NE</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">7</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Meta Platforms Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">58.5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">189.5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Communication Services</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Menlo Park, CA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">8</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">JPMorgan Chase &amp; Co.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">56.7</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">277.7</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Financials</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">New York, NY</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">9</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Exxon Mobil Corporation</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">30.0</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">324.9</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Energy</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Irving, TX</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">10</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Bank of America Corporation</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">28.3</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">188.8</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Financials</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Charlotte, NC</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">11</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Johnson &amp; Johnson</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">25.1</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">92.1</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Health Care</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">New Brunswick, NJ</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">12</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Comcast Corporation</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">22.6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">123.3</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Communication Services</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Philadelphia, PA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">13</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">AT&amp;T Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">22.2</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">124.5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Communication Services</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Dallas, TX</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">14</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Walmart Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">21.3</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">693.2</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Consumer Staples</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Bentonville, AR</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">15</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Wells Fargo &amp; Company</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">20.0</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">122.6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Financials</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">San Francisco, CA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">16</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Visa Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">19.9</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">40.0</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Financials</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">San Francisco, CA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">17</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Verizon Communications Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">19.8</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">137.5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Communication Services</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">New York, NY</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">18</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Broadcom Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">18.9</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">59.9</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Information Technology</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Palo Alto, CA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">19</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Eli Lilly and Company</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">18.4</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">59.4</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Health Care</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Indianapolis, IN</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">20</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">UnitedHealth Group Incorporated</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">17.6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">435.2</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Health Care</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Minnetonka, MN</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">21</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Uber Technologies Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">16.6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">49.6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Industrials</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">San Francisco, CA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">22</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Procter &amp; Gamble Company</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">16.5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">84.9</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Consumer Staples</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Cincinnati, OH</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">23</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Merck &amp; Co. Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">16.4</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">63.6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Health Care</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Rahway, NJ</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">24</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Goldman Sachs Group Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">15.8</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">127.2</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Financials</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">New York, NY</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">25</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Home Depot Inc.</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">14.6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">165.1</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Consumer Discretionary</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Atlanta, GA</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">26</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Mastercard Incorporated</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">14.3</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">31.5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Financials</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Purchase, NY</span></td></tr>

In [6]:
table2 = soup.find_all('table')[1]

In [7]:
table2.find_all('th')

[<th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Rank</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Company Name</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Net Profit ($B)</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Revenue ($B)</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Industry</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Headquarters</span></th>]

In [8]:
table_header = table2.find_all('th')

In [9]:
world_table_header = [title.text for title in table_header]

In [10]:
world_table_header

['Rank',
 'Company Name',
 'Net Profit ($B)',
 'Revenue ($B)',
 'Industry',
 'Headquarters']

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(columns = world_table_header)

In [13]:
df

Empty DataFrame
Columns: [Rank, Company Name, Net Profit ($B), Revenue ($B), Industry, Headquarters]
Index: []

In [14]:
column_data = table2.find_all('tr')

In [15]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

In [16]:
df

,Rank,Company Name,Net Profit ($B),Revenue ($B),Industry,Headquarters
0,1,Alphabet Inc.,124.3,385.5,Communication Services,"Mountain View, CA"
1,2,Apple Inc.,112.0,416.2,Information Technology,"Cupertino, CA"
2,3,Microsoft Corporation,104.9,293.8,Information Technology,"Redmond, WA"
3,4,NVIDIA Corporation,86.6,165.2,Information Technology,"Santa Clara, CA"
4,5,Amazon.com Inc.,76.5,691.3,Consumer Discretionary,"Seattle, WA"
5,6,Berkshire Hathaway Inc.,67.5,372.1,Financials,"Omaha, NE"
6,7,Meta Platforms Inc.,58.5,189.5,Communication Services,"Menlo Park, CA"
7,8,JPMorgan Chase & Co.,56.7,277.7,Financials,"New York, NY"
8,9,Exxon Mobil Corporation,30.0,324.9,Energy,"Irving, TX"
9,10,Bank of America Corporation,28.3,188.8,Financials,"Charlotte, NC"
10,11,Johnson & Johnson,25.1,92.1,Health Care,"New Brunswick, NJ"
11,12,Comcast Corporation,22.6,123.3,Communication Services,"Philadelphia, PA"
12,13,AT&T Inc.,22.2,124.5,Communication Services,"Dallas, TX"
13,14,Walmart Inc.,21.3,693.2,Consumer Staples,"Bentonville, AR"
14,15,Wells Fargo & Company,20.0,122.6,Financials,"San Francisco, CA"
15,16,Visa Inc.,19.9,40.0,Financials,"San Francisco, CA"
16,17,Verizon Communications Inc.,19.8,137.5,Communication Services,"New York, NY"
17,18,Broadcom Inc.,18.9,59.9,Information Technology,"Palo Alto, CA"
18,19,Eli Lilly and Company,18.4,59.4,Health Care,"Indianapolis, IN"
19,20,UnitedHealth Group Incorporated,17.6,435.2,Health Care,"Minnetonka, MN"
20,21,Uber Technologies Inc.,16.6,49.6,Industrials,"San Francisco, CA"
21,22,Procter & Gamble Company,16.5,84.9,Consumer Staples,"Cincinnati, OH"
22,23,Merck & Co. Inc.,16.4,63.6,Health Care,"Rahway, NJ"
23,24,Goldman Sachs Group Inc.,15.8,127.2,Financials,"New York, NY"
24,25,Home Depot Inc.,14.6,165.1,Consumer Discretionary,"Atlanta, GA"
25,26,Mastercard Incorporated,14.3,31.5,Financials,"Purchase, NY"
26,27,Morgan Stanley,14.1,113.0,Financials,"New York, NY"
27,28,Abbott Laboratories,14.0,43.8,Health Care,"Chicago, IL"
28,29,Chevron Corporation,13.7,187.7,Energy,"San Ramon, CA"
29,30,Citigroup Inc.,13.4,168.3,Financials,"New York, NY"
30,31,Coca-Cola Company,13.0,47.7,Consumer Staples,"Atlanta, GA"
31,32,Oracle Corporation,12.4,59.0,Information Technology,"Austin, TX"
32,33,T-Mobile US Inc.,11.9,85.8,Communication Services,"Bellevue, WA"
33,34,Walt Disney Company,11.6,94.5,Communication Services,"Burbank, CA"
34,35,Progressive Corporation,10.7,85.2,Financials,"Mayfield Village, OH"
35,36,Netflix Inc.,10.4,43.4,Communication Services,"Los Gatos, CA"
36,37,American Express Company,10.4,75.9,Financials,"New York, NY"
37,38,Cisco Systems Inc.,10.2,56.7,Information Technology,"San Jose, CA"
38,39,Pfizer Inc.,9.8,62.8,Health Care,"New York, NY"
39,40,Caterpillar Inc.,9.3,64.7,Industrials,"Deerfield, IL"
40,41,ConocoPhillips,9.2,57.8,Energy,"Houston, TX"
41,42,Altria Group Inc.,8.8,23.4,Consumer Staples,"Richmond, VA"
42,43,Philip Morris International Inc.,8.6,40.0,Consumer Staples,"Stamford, CT"
43,44,Micron Technology Inc.,8.5,37.4,Information Technology,"Boise, ID"
44,45,McDonald's Corporation,8.4,26.3,Consumer Discretionary,"Chicago, IL"
45,46,Gilead Sciences Inc.,8.1,29.1,Health Care,"Foster City, CA"
46,47,Costco Wholesale Corporation,8.1,275.2,Consumer Staples,"Issaquah, WA"
47,48,General Electric Company,8.1,43.9,Industrials,"Boston, MA"
48,49,International Business Machines Corporation,7.9,65.4,Information Technology,"Armonk, NY"
49,50,MicroStrategy Incorporated,7.7,0.5,Information Technology,"Tysons Corner, VA"

In [17]:
soup.find_all('table')[0]

<table class="w-full border-collapse text-sm"><thead class="border-border-l1 border-b bg-surface-l1"><tr class="divide-border-l1 divide-x bg-surface-l1"><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Rank</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Company Name</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Revenue ($B)</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Industry</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Headquarters State</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">CEO</span></th></tr>
</thead><tbody class="divide-border-l1 divide-y"><tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">1</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Walmart</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">681</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Retail</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Arkansas</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Doug McMillon</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">2</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Amazon</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">638</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">E-commerce</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Washington</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Andy Jassy</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">3</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">UnitedHealth Group</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">400</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Healthcare</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Minnesota</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Andrew Witty</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">4</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Apple</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">391</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Technology</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">California</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Tim Cook</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">CVS Health</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">373</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Healthcare</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Rhode Island</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Karen S. Lynch</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Berkshire Hathaway</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">371</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Conglomerate</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Nebraska</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Warren Buffett</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">7</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Alphabet</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">350</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Technology</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">California</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Sundar Pichai</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">8</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">ExxonMobil</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">350</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Energy</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Texas</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Darren Woods</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">9</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">McKesson</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">309</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Healthcare</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Texas</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Brian Tyler</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">10</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Cencora</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">294</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Healthcare</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Pennsylvania</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Steven H. Collis</span></td></tr>
</tbody></table>

In [19]:
table1 = soup.find_all('table')[0]

In [20]:
table1.find_all('th')

[<th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Rank</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Company Name</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Revenue ($B)</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Industry</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Headquarters State</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">CEO</span></th>]

In [21]:
table_header1 = table1.find_all('th')

In [22]:
world_table_header1 = [title.text for title in table_header1]

In [24]:
world_table_header1

['Rank',
 'Company Name',
 'Revenue ($B)',
 'Industry',
 'Headquarters State',
 'CEO']

In [25]:
import pandas as pd

In [26]:
df = pd.DataFrame(columns = world_table_header1)

In [27]:
df

Empty DataFrame
Columns: [Rank, Company Name, Revenue ($B), Industry, Headquarters State, CEO]
Index: []

In [29]:
column_data1 = table1.find_all('tr')

In [30]:
for row in column_data1[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

In [31]:
df

,Rank,Company Name,Revenue ($B),Industry,Headquarters State,CEO
0,1,Walmart,681,Retail,Arkansas,Doug McMillon
1,2,Amazon,638,E-commerce,Washington,Andy Jassy
2,3,UnitedHealth Group,400,Healthcare,Minnesota,Andrew Witty
3,4,Apple,391,Technology,California,Tim Cook
4,5,CVS Health,373,Healthcare,Rhode Island,Karen S. Lynch
5,6,Berkshire Hathaway,371,Conglomerate,Nebraska,Warren Buffett
6,7,Alphabet,350,Technology,California,Sundar Pichai
7,8,ExxonMobil,350,Energy,Texas,Darren Woods
8,9,McKesson,309,Healthcare,Texas,Brian Tyler
9,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis

In [32]:
soup.find_all('table')[2]

<table class="w-full border-collapse text-sm"><thead class="border-border-l1 border-b bg-surface-l1"><tr class="divide-border-l1 divide-x bg-surface-l1"><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Rank</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Company Name</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Estimated Revenue ($B USD)</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Industry</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Headquarters State</span></th><th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Founder/Owner</span></th></tr>
</thead><tbody class="divide-border-l1 divide-y"><tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">1</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Cargill">Cargill</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">160</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Agriculture">Agriculture</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Minnesota">Minnesota</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Cargill_family">Cargill family</a></span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">2</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Koch Industries</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">125</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Diversified</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Kansas">Kansas</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Koch_family">Koch family</a></span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">3</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Publix">Publix</a> Super Markets</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">57.1</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Retail</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Florida">Florida</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Employee-owned</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">4</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Mars</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">50</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Food</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Virginia</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Mars_family">Mars family</a></span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/H-E-B">H-E-B</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">46.5</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Retail</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Texas">Texas</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Butt family</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">6</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Reyes_Holdings">Reyes Holdings</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">40</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Distribution</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Illinois">Illinois</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Reyes family</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">7</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Enterprise Mobility</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">38</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Transportation</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Missouri">Missouri</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Taylor family</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">8</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/C&amp;S_Wholesale_Grocers">C&amp;S Wholesale Grocers</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">34</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Wholesale</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/New_Hampshire">New Hampshire</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Cohen family</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">9</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Fidelity_Investments">Fidelity Investments</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">28.2</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Finance</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Massachusetts">Massachusetts</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Johnson family</span></td></tr>
<tr class="divide-border-l1 divide-x bg-surface-l1"><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">10</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Southern Glazer's Wine &amp; Spirits</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">26</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]">Distribution</span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Florida">Florida</a></span></td><td class="text-fg-primary px-2 py-1 align-top"><span class="text-[1em] leading-[1.85]"><a class="break-words text-[1em] text-blue-500 hover:underline dark:text-blue-200" href="/page/Chaplin_family">Chaplin family</a></span></td></tr>
</tbody></table>

In [33]:
table3 = soup.find_all('table')[2]

In [34]:
table3.find_all('th')

[<th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Rank</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Company Name</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Estimated Revenue ($B USD)</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Industry</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Headquarters State</span></th>,
 <th class="dark:text-fg-primary bg-gray-100 px-2 py-1 text-left align-top font-bold dark:bg-black"><span class="text-[1em] leading-[1.85]">Founder/Owner</span></th>]

In [35]:
table_header3 = table3.find_all('th')

In [36]:
world_title_header3 = [title.text for title in table_header3]

In [37]:
world_title_header3

['Rank',
 'Company Name',
 'Estimated Revenue ($B USD)',
 'Industry',
 'Headquarters State',
 'Founder/Owner']

In [38]:
import pandas as pd

df = pd.DataFrame(columns = world_title_header3)

In [39]:
df

Empty DataFrame
Columns: [Rank, Company Name, Estimated Revenue ($B USD), Industry, Headquarters State, Founder/Owner]
Index: []

In [43]:
column_data3 = table3.find_all('td')

In [44]:
for row in column_data3[1:]:
    row_data in row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

In [45]:
df

,Rank,Company Name,Estimated Revenue ($B USD),Industry,Headquarters State,Founder/Owner
0,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis
1,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis
2,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis
3,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis
4,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis
...,...,...,...,...,...,...
64,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis
65,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis
66,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis
67,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis
68,10,Cencora,294,Healthcare,Pennsylvania,Steven H. Collis